# Generated by Django 5.2.7 on 2025-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_cartitem_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
